### ISSUE TITLE
Where to download the pre-computed features for the training split?

### ISSUE THREAD

**Issue by jianhua2022** [BCV-Uniandes/PNG#4]
Hi, 
 This is a very interesting work. I cannot train the model because pre-computed features are not available for the training split. So whether you plan to release the training features?

Thanks!

**Comment by cigonzalez** [comment]
Hi,

Thanks for your interest in our work! 
We do not release the pre-computed features for the training split because of their size. However, I just included the code for generating the features for each data split in this repository. Additionally, I added more details in the README about it.

Just let me know if you have any questions.

Best,
Cristina González
